# Generated by Django 5.2.4 on 2025-08-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name (Arabic)'),
        ),
    ]
